### ISSUE TITLE
Argument error in regular expression

### ISSUE THREAD

**Issue by adaliszk** [VoronyukM/issue_id#8]
```
ArgumentError: The provided regular expression is using multiline anchors (^ or $), which may present a security risk. Did you mean to use \A and \z, or forgot to add the :multiline => true option?
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.8/lib/active_model/validations/format.rb:39:in `check_options_validity'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.8/lib/active_model/validations/format.rb:20:in `check_validity!'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.8/lib/active_model/validator.rb:141:in `initialize'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.8/lib/active_model/validations/with.rb:92:in `new'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.8/lib/active_model/validations/with.rb:92:in `block in validates_with'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.8/lib/active_model/validations/with.rb:91:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.8/lib/active_model/validations/with.rb:91:in `validates_with'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.8/lib/active_model/validations/format.rb:109:in `validates_format_of'
/home/redmine/redmine/plugins/issue_id/lib/issue_project_patch.rb:16:in `block in included'
/home/redmine/redmine/plugins/issue_id/lib/issue_project_patch.rb:8:in `class_eval'
/home/redmine/redmine/plugins/issue_id/lib/issue_project_patch.rb:8:in `included'
/home/redmine/redmine/plugins/issue_id/init.rb:45:in `include'
/home/redmine/redmine/plugins/issue_id/init.rb:45:in `block in <top (required)>'
```

**Comment by igor-panassiouk** [comment]
same error during installation
Redmine 3.3.1 on Debian

**Comment by VoronyukM** [comment]
Hi @adaliszk  and @igor-panassiouk , I'm not an author of the plugin and I've not tested the plugin with Redmine different from 2.5. I'm a kind of a user that fixes his own issues in this repo. I'd recommend you to try the latest version from the source SVN repo http://projects.andriylesyuk.com/projects/issue-id/repository
and/or to ask your question directly to the author in his issue tracker http://projects.andriylesyuk.com/projects/issue-id/issues
I think in that cases you may get more helpful answer.

Or, you can clone this repo, fetch last changes from SVN repo, (optionally) fix some issues and make a pull request.
